name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ejecutar tests
        run: |
          ./test.sh || true

          # Verifica si el archivo pruebas_fallidas.txt está vacío
          if [ $(cat pruebas_fallidas.txt | wc -c) -ne 0 ]; then
              echo "Tests failed. See pruebas_fallidas.txt for details." >&2
              echo < pruebas_fallidas.txt >&2
          else
              echo "All tests passed."
          fi
      
      - name: Listar archivos
        run: ls -R

      - name: Guardar artefactos
        uses: actions/upload-artifact@v3
        with:
          name: estado-final
          path: pruebas_fallidas.txt

  review:
    runs-on: ubuntu-latest
    needs: test  # El job depende de la ejecución anterior
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v3
        with:
          name: estado-final

      - name: Exito o fallo
        run: |
          if [ $(cat pruebas_fallidas.txt | wc -c) -ne 0 ]; then
              exit 1
          else
              exit 0
