name: Run Tests

on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Verificar la instalación de Java
        run: java -version

      - name: Verificar la instalación de Kotlin
        run: kotlinc -version

      - name: Hacer el script de tests ejecutable
        run: chmod +x test.sh 

      - name: Ejecutar tests
        run: |
          source .bashrc
          chmod +x bin/*.sh
          test.sh || true

          # Verifica si el archivo pruebas_fallidas.log está vacío
          if [ -f pruebas_fallidas.log ]; then
              echo "Tests failed. See pruebas_fallidas.log for details." >&2
              cat pruebas_fallidas.log >&2
          else
              echo -e "\e[32m\e[1mAll tests passed.\e[0m"
          fi
      
      - name: Listar archivos
        run: ls -R

      - name: Exito o fallo
        run: |
          if [ -f pruebas_fallidas.log ]; then
              exit 1
          else
              exit 0
          fi

      - name: Verificar que los problemas probados manualmente den AC
        run: |
          source .bashrc
          detect_outdated_acs.sh